version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8081:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
